# Generated by Django 6.0 on 2026-03-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0080_event_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mwacorrelator',
            name='repointing_threshold',
            field=models.FloatField(help_text='In the case that an observation has already been requested, request a new observation only if the updated pointing coordinates differ by more than this threshold. [degree]'),
        ),
        migrations.AlterField(
            model_name='mwagw',
            name='repointing_threshold',
            field=models.FloatField(help_text='In the case that an observation has already been requested, request a new observation only if the updated pointing coordinates differ by more than this threshold. [degree]'),
        ),
        migrations.AlterField(
            model_name='mwavcs',
            name='repointing_threshold',
            field=models.FloatField(help_text='In the case that an observation has already been requested, request a new observation only if the updated pointing coordinates differ by more than this threshold. [degree]'),
        ),
    ]
