# Generated by Django 6.0 on 2026-05-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0081_alter_mwacorrelator_repointing_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('domain', models.CharField(max_length=500)),
                ('config', models.JSONField(default=dict)),
            ],
        ),
    ]
