# Generated by Django 6.0 on 2026-05-20 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0082_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='topics', to='tracet.stream'),
        ),
    ]
