# Generated by Django 6.0 on 2026-05-20 06:49
import os

from django.db import migrations


def create_parent_stream(apps, schema_editor):
    # We have added Streams as a new parent type to Topics - and thus allowing multiple
    # configurable streams - but there are a number of pre-existing topics that were
    # hard-coded to work with GCN.
    #
    # In this migration, if there are pre-existing topics, we create a default GCN Steam
    # and set existing Topics to point to this stream.
    #
    # In the next migration, we will make the Topic foriegn key non-nullable.

    Stream = apps.get_model("tracet", "Stream")
    Topic = apps.get_model("tracet", "Topic")

    topics = list(Topic.objects.filter(stream__isnull=True))
    if len(topics):
        stream = Stream.objects.create(name="GCN", domain="kafka.gcn.nasa.gov", config={
            "security.protocol": "sasl_ssl",
            "sasl.mechanism": "OAUTHBEARER",
            "sasl.oauthbearer.method": "oidc",
            "sasl.oauthbearer.client.id": os.getenv("GCN_CLIENT_ID"),
            "sasl.oauthbearer.client.secret": os.getenv("GCN_CLIENT_SECRET"),
            "sasl.oauthbearer.token.endpoint.url": "https://auth.gcn.nasa.gov/oauth2/token",
        })

        for topic in topics:
            topic.stream = stream
            topic.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0083_topic_stream'),
    ]



    operations = [
        migrations.RunPython(create_parent_stream)
    ]
