# Generated by Django 6.0 on 2026-05-20 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0084_auto_20260520_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='topics', to='tracet.stream'),
        ),
    ]
