# Generated by Django 6.0 on 2026-05-20 07:41

import tracet.models.stream
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0085_alter_topic_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stream',
            name='last_polled',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='config',
            field=models.JSONField(default=dict, encoder=tracet.models.stream.PrettyJSONEncoder),
        ),
    ]
