# Generated by Django 6.0 on 2026-05-21 07:26

import tracet.models.stream
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0086_stream_enabled_stream_last_polled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='config',
            field=models.JSONField(default=dict, encoder=tracet.models.stream.PrettyJSONEncoder, null=True),
        ),
    ]
