# Generated by Django 6.0 on 2026-05-21 07:30

import tracet.models.stream
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0087_alter_stream_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='config',
            field=models.JSONField(blank=True, default=dict, encoder=tracet.models.stream.PrettyJSONEncoder, null=True),
        ),
    ]
