# Generated by Django 6.0 on 2026-05-21 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0088_alter_stream_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='last_polled',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
