# Generated by Django 6.0 on 2026-05-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0089_alter_stream_last_polled'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='ATCA',
                ),
                migrations.DeleteModel(
                    name='ATCABand',
                ),
            ]
        ),
    ]
