# Generated by Django 6.0 on 2026-05-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0090_remove_atca_trigger_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='MWACorrelator',
                ),
                migrations.DeleteModel(
                    name='MWAGW',
                ),
                migrations.DeleteModel(
                    name='MWAVCS',
                ),
            ]
        ),
    ]
