# Generated by Django 6.0 on 2026-05-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0091_remove_mwagw_trigger_remove_mwavcs_trigger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observatory',
            field=models.CharField(max_length=500),
        ),
    ]
