# Generated by Django 6.0 on 2026-05-29 03:27

import django.db.models.deletion
import tracet.models.stream
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0092_alter_observation_observatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='config',
            field=models.JSONField(blank=True, default=dict, encoder=tracet.models.stream.PrettyJSONEncoder, help_text='A JSON dictionary that maps Kafka configuration names to values. e.g.: <code>{"parameter1": "value1", "parameter2": "value2"}</code>. Each Kafka broker may need one or more additional configuration parameters depending on its particular setup.<br><br>Full documentation of the configuration options is available at <a href=\'https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html\'>https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html</a>', null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='domain',
            field=models.CharField(help_text="The domain(s) of the Kafka message broker in the format <code>DOMAIN:PORT</code>. If omitted, the port will default to 9092. This value corresponds to Kafka's <code>bootstrap.servers</code> configuration parameter.<br><br>Some Kafka brokers use multiple domains for fault tolerance and these can be provided as a comma-separated list, e.g. <code>DOMAIN1:PORT1,DOMAIN2:PORT2,...</code>. ", max_length=500),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(help_text='A short descriptive name for this stream.', max_length=500),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(help_text='The topic name as set by the Kafka message broker. e.g. <code>gcn.notices.svom.voevent.eclairs</code>', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='stream',
            field=models.ForeignKey(help_text='Select the stream to which this topic belongs.', on_delete=django.db.models.deletion.RESTRICT, related_name='topics', to='tracet.stream'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.CharField(choices=[('xml', 'XML'), ('json', 'JSON')], default='xml', help_text="The payload format of this topic's notices. TraceT can parse both JSON and XML payloads. This type must match the format of the incoming notices, and it will determine whether a Trigger uses XPath or JPath queries.", max_length=500, verbose_name='Format'),
        ),
    ]
