# Generated by Django 6.0 on 2026-05-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0093_alter_stream_config_alter_stream_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
