# Generated by Django 6.0 on 2026-05-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0094_topic_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='decision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='tracet.decision'),
        ),
    ]
