# Generated by Django 6.0 on 2026-06-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0095_alter_observation_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(help_text='The topic name as set by the Kafka message broker. e.g. <code>gcn.notices.svom.voevent.eclairs</code>', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'stream')},
        ),
    ]
