# Generated by Django 6.0 on 2026-06-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0096_alter_topic_name_alter_topic_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='expiry',
            field=models.FloatField(help_text='Events will expire once this duration has elapsed since the event time. More specifically: for a given event time (T0), a notice received at a later time (T1) will only trigger an observation if (T1 - T0 < expiry). Manual retriggers will ignore this condition. [minute]'),
        ),
    ]
