# Generated by Django 6.0 on 2026-05-26 03:34

import django.db.models.deletion
import tracet.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracet', '0090_remove_atca_trigger_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ATCA',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('projectid', models.CharField(max_length=500)),
                        ('http_username', models.CharField(max_length=500, verbose_name='HTTP Username')),
                        ('http_password', models.CharField(max_length=500, verbose_name='HTTP Password')),
                        ('email', models.EmailField(help_text='The email address that was supplied in the NAPA proposal.', max_length=254)),
                        ('authentication_token', models.CharField(max_length=500)),
                        ('ra_path', tracet.fields.JXPathField(help_text='The (x|j)path to the Right Ascension. This value is set by the most recent matching notice.', max_length=500)),
                        ('dec_path', tracet.fields.JXPathField(help_text='The (x|j)path to the Declination. This value is set by the most recent matching notice.', max_length=500)),
                        ('maximum_lag', models.FloatField(help_text='The maximum delay allowed for scheduling this observation. If the observation cannot be scheduled to start within this time, it will not be scheduled at all. [minute]')),
                        ('minimum_exposure', models.IntegerField(help_text='The minimum exposure time required for this trigger. The trigger will be rejected if ATCA cannot schedule a total exposure of at least this time. [minute]')),
                        ('maximum_exposure', models.IntegerField(help_text='The maximum exposure time required for this trigger. [minute]')),
                        ('trigger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='tracet.trigger')),
                    ],
                    options={
                        'db_table': 'tracet_atca',
                    },
                ),
                migrations.CreateModel(
                    name='ATCABand',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('band', models.IntegerField(choices=[(3, '3mm'), (7, '6mm'), (15, '15mm'), (40, '4cm'), (160, '16cm')])),
                        ('exposure', models.IntegerField(help_text='The exposure time of this reciever. Receivers will be continuously cycled up until the full scheduled slot is exhausted. [minute]')),
                        ('freq1', models.IntegerField(help_text='Specify the central frequency for the first of the 2 GHz bands at which this receiver will observe. Note: the 16 cm reciever can only observe at 2100 MHz. [MHz]', verbose_name='Frequency 1')),
                        ('freq2', models.IntegerField(help_text='Specify the central frequency for the second of the 2 GHz bands at which this receiver will observe. Note: the 16 cm reciever can only observe at 2100 MHz. [MHz]', verbose_name='Frequency 2')),
                        ('atca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atcabands', to='atca.atca')),
                    ],
                    options={
                        'db_table': 'tracet_atcaband',
                        'constraints': [models.UniqueConstraint(fields=('atca', 'band'), name='unique wavelength configuration')],
                    },
                ),
            ]
        ),
    ]
