# Generated by Django 6.0 on 2026-05-26 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atca',
            table=None,
        ),
        migrations.AlterModelTable(
            name='atcaband',
            table=None,
        ),
    ]
