# Generated by Django 6.0 on 2026-08-18 06:43

import tracet.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atca', '0002_alter_atca_table_alter_atcaband_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='atca',
            name='authentication_token_encrypted',
            field=tracet.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
