# Generated by Django 6.0 on 2026-08-18 06:56

from django.db import migrations


def encrypt_forward(apps, schema_editor):
    cls = apps.get_model("atca", "ATCA")

    for obj in cls.objects.all().iterator():
        if obj.authentication_token:
            obj.authentication_token_encrypted = obj.authentication_token
            obj.save(update_fields=["authentication_token_encrypted"])


def encrypt_backward(apps, schema_editor):
    cls = apps.get_model("atca", "ATCA")

    for obj in cls.objects.all().iterator():
        if obj.authentication_token_encrypted:
            obj.authentication_token = obj.authentication_token_encrypted
            obj.save(update_fields=["authentication_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("atca", "0003_atca_authentication_token_encrypted"),
    ]

    operations = [
        migrations.RunPython(encrypt_forward, encrypt_backward),
    ]
