# Generated by Django 6.0 on 2026-08-18 07:02

import tracet.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atca', '0004_auto_20260818_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atca',
            name='authentication_token',
        ),
        migrations.RenameField(
            model_name='atca',
            old_name='authentication_token_encrypted',
            new_name='authentication_token',
        ),
    ]
