# Generated by Django 6.0 on 2026-08-18 06:42

import tracet.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwa', '0002_alter_mwacorrelator_table_alter_mwagw_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwacorrelator',
            name='secure_key_encrypted',
            field=tracet.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mwagw',
            name='secure_key_encrypted',
            field=tracet.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mwavcs',
            name='secure_key_encrypted',
            field=tracet.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
