# Generated by Django 6.0 on 2026-08-18 06:46

from django.db import migrations


def encrypt_forward(apps, schema_editor):
    for modelname in ("MWACorrelator", "MWAGW", "MWAVCS"):
        cls = apps.get_model("mwa", modelname)

        for obj in cls.objects.all().iterator():
            if obj.secure_key:
                obj.secure_key_encrypted = obj.secure_key
                obj.save(update_fields=["secure_key_encrypted"])


def encrypt_backward(apps, schema_editor):
    for modelname in ("MWACorrelator", "MWAGW", "MWAVCS"):
        cls = apps.get_model("mwa", modelname)

        for obj in cls.objects.all().iterator():
            if obj.secure_key_encrypted:
                obj.secure_key = obj.secure_key_encrypted
                obj.save(update_fields=["secure_key"])


class Migration(migrations.Migration):
    dependencies = [
        ("mwa", "0003_mwacorrelator_secure_key_encrypted_and_more"),
    ]

    operations = [
        migrations.RunPython(encrypt_forward, encrypt_backward),
    ]
