# Generated by Django 6.0 on 2026-08-18 07:02

import tracet.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwa', '0004_auto_20260818_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mwacorrelator',
            name='secure_key',
        ),
        migrations.RemoveField(
            model_name='mwagw',
            name='secure_key',
        ),
        migrations.RemoveField(
            model_name='mwavcs',
            name='secure_key',
        ),
        migrations.RenameField(
            model_name='mwacorrelator',
            old_name='secure_key_encrypted',
            new_name='secure_key',
        ),
        migrations.RenameField(
            model_name='mwagw',
            old_name='secure_key_encrypted',
            new_name='secure_key',
        ),
        migrations.RenameField(
            model_name='mwavcs',
            old_name='secure_key_encrypted',
            new_name='secure_key',
        ),
    ]
